version: '3.8'
services:
  back:
    container_name: loja_backend
    env_file:
      - ./backend/.env.database
      - ./backend/.env
    restart: unless-stopped
    expose:
      - ${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    build:
      context: ./backend
    volumes:
    - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - loja_network
    environment:
      - NODE_ENV=${NODE_ENV}
  
  front:
    container_name: loja_frontend
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    expose:
      - 3000
    build:
      context: frontend
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - back
    networks:
      - loja_network
    environment:
      - NODE_ENV=${NODE_ENV}

  db:
    image: mysql:8
    container_name: loja_database
    env_file:
      - ./backend/.env.database
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:3306
    expose:
      - ${DATABASE_PORT}
    volumes:
      - mysql_loja_db:/var/lib/mysql
      - mysql_loja_db_config:/etc/mysql
    networks:
      - loja_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  loja_network:
    driver: bridge

volumes:
  mysql_loja_db:
  mysql_loja_db_config: